export const GET_ERRORS = "GET_ERRORS";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const SEARCH_FRIENDS_SUCCESS = "SEARCH_FRIENDS_SUCCESS";
export const ADD_FRIEND_SUCCESS = "ADD_FRIEND_SUCCESS";
export const GET_FRIENDS_POSTS_SUCCESS = "GET_FRIENDS_POSTS_SUCCESS";
export const GET_FRIENDS_POST_SUCCESS = "GET_FRIENDS_POST_SUCCESS";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";

